### ISSUE TITLE
Enhancement: add an option to Search List to check for max price as well.

### ISSUE THREAD

**Issue by keijodputt** [Greeenman999/LibrarianTradeFinder#15]
In the config GUI there's an option to select a set of enchantments to search through. This method is set to stop/notify when a desired enchant is found, regardless of its cost in emeralds.
My request is to have a field in which we can stipulate how much the max price has to be for each of the items we select. The rationale behind this is that it would be way faster to find a suitable deal with the desired amount of ems if we can add the max it the list as well.

It's known, in vanilla, that the price in emeralds depends on the enchantment level and "treasure" (Mending, Frost Walker) status. The list always goes for the enchantment level, ignoring the cost in emeralds, so according to this premise:
  - 5–19 for Lvl I,
  - 8–32 for Lvl II,
  - 11–45 for Lvl III
  - 14–58 for Lvl IV
  - 17–64 (capped) for Lvl V
  - Double price for any 'treasure enchantment', so Mending/Frost Walker will cost 10–38 ems and Frost Walker II will be 16–64

Is it doable?

Thanks.-

**Comment by Greeenman999** [comment]
Hi, I'm currently working on a new gui, it should be done in a few weeks, because unfortunately I am on vacation right now...
The gui is going to contain the feature you suggested :) 

Have a great day/morning/evening!

**Comment by SzczurekYT** [comment]
Until the GUI update, you can use my build.
It has /tradefinder searchList <maxPrice>, that works like searchSingle - if you type /tradefinder searchList 25, it will look for any enchantment on the list that cost 25 or less emeralds.
It's not as good as your idea, but better then nothing, and may work as a temporary solution.
Due to github limits I have to upload the file as a .zip file, you need to rename it back to .jar.
[librarian-trade-finder-1.2.3.zip](https://github.com/Greeenman999/LibrarianTradeFinder/files/11238921/librarian-trade-finder-1.2.3.zip)

**Comment by Greeenman999** [comment]
Released it
